# when@dev:
#     _errors:
#         resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
#         prefix: /_error

# index:
#     path: /name
#     controller: App\Controller\PostController::index
